In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [25]:
peruanos = 10.
colombianos = 2.

for i in range(500):
    nums = np.ones(peruanos+colombianos)
    nums[:10] = 0
    np.random.shuffle(nums)
    print nums, len(nums)
    np.append(nums,nums[0])
    print len(nums)
    contador = 0.
    for j in range(len(nums)-1):
        if(nums[i]==0 and nums[i-1]==1 and nums[i+1]==1):
            contador +=1
    print contador    

[ 1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.] 12
12
0.0
[ 0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.] 12
12
0.0
[ 1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.] 12
12
0.0
[ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.] 12
12
0.0
[ 0.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.] 12
12
0.0
[ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  1.] 12
12
0.0
[ 0.  0.  0.  1.  0.  0.  0.  0.  1.  0.  0.  0.] 12
12
0.0
[ 1.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.] 12
12
0.0
[ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  1.  0.] 12
12
0.0
[ 0.  1.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.] 12
12
0.0
[ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  1.  0.] 12
12
0.0
[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  1.] 12
12
0.0
[ 0.  0.  0.  1.  0.  0.  0.  0.  0.  1.  0.  0.] 12
12


IndexError: index 12 is out of bounds for axis 0 with size 12

In [41]:
a = np.array([])
print len(a)
a =np.append(a,1)
print a,len(a)

0
[ 1.] 1


In [30]:
np.append?